# Generated by Django 4.1 on 2023-06-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postitnotapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addnot",
            name="author",
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
